version: '3.3'
services:

  web:
    image: hammer/sagemaker:latest
    volumes:
      - ${PWD}/.jupyter:/home/sagemaker-user/.jupyter
      - ~/.aws:/home/sagemaker-user/.aws
      - ~/.gitconfig:/home/sagemaker-user/.gitconfig
      - ~/.git-credentials:/home/sagemaker-user/.git-credentials
    environment:
      - PYTHONPATH=/home/sagemaker-user/SageMaker/mllib
    ports:
      - 8081:8888
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    networks:
      - mynet

networks:
  mynet:


