FROM public.ecr.aws/docker/library/adminer:latest

COPY login-servers-custom.php /var/www/html/plugins/login-servers-custom.php
COPY 000-login-servers-custom.php /var/www/html/plugins-enabled/000-login-servers-custom.php
