version: '3.3'

services:

  webs:
    image: ietty/nlp:2022031901
    deploy:
      #mode: global
      mode: replicated
      replicas: 1
    ports:
      - 8096:8888
    command: jupyter lab --ip=0.0.0.0 --no-browser

